package com.example.red30.compose.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF9F0011)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDD1F26)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF520012)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF851E2E)
val onSecondaryContainerLight = Color(0xFFFFD5D6)
val tertiaryLight = Color(0xFF006A68)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF78CCCA)
val onTertiaryContainerLight = Color(0xFF003736)
val errorLight = Color(0xFFA23F16)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFC8254)
val onErrorContainerLight = Color(0xFF350B00)
val backgroundLight = Color(0xFFFFF8F7)
val onBackgroundLight = Color(0xFF281715)
val surfaceLight = Color(0xFFFCF8F8)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFE0E3E3)
val onSurfaceVariantLight = Color(0xFF444748)
val outlineLight = Color(0xFF747878)
val outlineVariantLight = Color(0xFFC4C7C7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF4F0EF)
val inversePrimaryLight = Color(0xFFFFB4AC)
val surfaceDimLight = Color(0xFFDDD9D9)
val surfaceBrightLight = Color(0xFFFCF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3F2)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE5E2E1)

val primaryDark = Color(0xFFFFB4AC)
val onPrimaryDark = Color(0xFF680007)
val primaryContainerDark = Color(0xFFD1121F)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFFFB3B6)
val onSecondaryDark = Color(0xFF66031A)
val secondaryContainerDark = Color(0xFF650219)
val onSecondaryContainerDark = Color(0xFFFFA4A9)
val tertiaryDark = Color(0xFF90E5E2)
val onTertiaryDark = Color(0xFF003736)
val tertiaryContainerDark = Color(0xFF66BBB9)
val onTertiaryContainerDark = Color(0xFF002727)
val errorDark = Color(0xFFFFB59B)
val onErrorDark = Color(0xFF5B1A00)
val errorContainerDark = Color(0xFFE57044)
val onErrorContainerDark = Color(0xFF000000)
val backgroundDark = Color(0xFF1F0F0D)
val onBackgroundDark = Color(0xFFFCDBD7)
val surfaceDark = Color(0xFF141313)
val onSurfaceDark = Color(0xFFE5E2E1)
val surfaceVariantDark = Color(0xFF444748)
val onSurfaceVariantDark = Color(0xFFC4C7C7)
val outlineDark = Color(0xFF8E9192)
val outlineVariantDark = Color(0xFF444748)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E1)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFFC00017)
val surfaceDimDark = Color(0xFF141313)
val surfaceBrightDark = Color(0xFF3A3939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2A2A2A)
val surfaceContainerHighestDark = Color(0xFF353434)

val AvatarColors = listOf(
    primaryContainerLight,
    secondaryContainerLight,
    tertiaryContainerLight,
    errorContainerLight
)
